// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnnotationResponse = { boxes: Array<ObbBox>, warnings: Array<string>, };

export type ImageInfo = { index: number, filename: string, has_annotation: boolean, };

export type ObbBox = { class_id: number, points: [[number, number], [number, number], [number, number], [number, number]], };
